name: rust checks
on: [push, pull_request]
jobs:
  clippy:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        toolchain: [1.70.0]
        include:
          - os: windows-latest
            toolchain: 1.70.0-x86_64-pc-windows-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-clippy-${{ hashFiles('Cargo.lock', 'Cargo.toml') }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - uses: msys2/setup-msys2@v2
        with:
          release: false
          update: false
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            patch
        if: runner.os == 'Windows'
      - name: Update PATH
        run: |
          (Resolve-Path c:/msys64/mingw64/bin).Path >> $Env:GITHUB_PATH
        if: runner.os == 'Windows'
      # From https://github.com/actions-rs/clippy-check/pull/165
      - uses: kristof-mattei/clippy-check@9615027d0d038d93ede0037e3629366a5ba2ecf8
        with:
          args: -vv --features self-update -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.70.0
          components: rustfmt
      - run: cargo fmt -- --check

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        toolchain: [1.70.0, 1.60.0]
        include:
          - os: windows-latest
            toolchain: 1.70.0-x86_64-pc-windows-gnu
          - os: windows-latest
            toolchain: 1.60.0-x86_64-pc-windows-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.toolchain }}-test-${{ hashFiles('Cargo.lock', 'Cargo.toml') }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: msys2/setup-msys2@v2
        with:
          release: false
          update: false
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            patch
        if: runner.os == 'Windows'
      - name: Update PATH
        run: |
          (Resolve-Path c:/msys64/mingw64/bin).Path >> $Env:GITHUB_PATH
        if: runner.os == 'Windows'
      - run: cargo test
