name: taskcluster extra workers
on: [push]
jobs:
  osx:
    runs-on: macos-11
    env:
      secret: ${{ secrets.SECRET }}
      TC_WORKER_TYPE: osx
      PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.14'
      - run: python3 -m pip install pip==20.3.4 wheel==0.37.0 --upgrade
      - run: CI/start-worker.sh worker-$TC_WORKER_TYPE $TC_WORKER_TYPE
